[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "seshotake", email = "seshotake@gmail.com"},
]
dependencies = [
    "pygame>=2.1.2",
    "mypy>=0.991",
    "autopep8>=2.0.1",
]
requires-python = ">=3.10"
license = {text = "MIT"}
